name: Build for Android

on: [push]

env:
  CACHE_KEY_SUFFIX: v2
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kudo/ubuntu-nonroot:20.04
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: UTC
        NO_INTL: ${{ contains(matrix.variant, 'nointl') }}
        NO_JIT: ${{ !contains(matrix.variant, 'jit') }}

    steps:
      - name: Setup docker workspace
        run: |
            sudo sh -c "chown -R ubuntu $HOME"
            sudo sh -c "chmod 777 $GITHUB_WORKSPACE"
            # sudo sh -c "chmod 777 $GITHUB_WORKSPACE/../../_temp"
            sudo sh -c "chmod 777 /home"

      - uses: actions/checkout@v2

      - name: Setup Ubuntu environment
        run: |
          sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y sudo git php7.4-common libapache2-mod-php7.4
          git config --global user.email "git@job.com"; git config --global user.name "GitJob"

      - name: Setup Build  V8
        run: |
          ./scripts/setup-build.sh -r 9.2.230.18 android
          sudo apt-get install -y libatomic1-i386-cross && sudo sh -c 'echo "/usr/i686-linux-gnu/lib" >> /etc/ld.so.conf.d/i386-linux-gnu.conf' && sudo ldconfig

      - name: Build  V8
        run: |
          ./scripts/build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
