name: Build for Android

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      # max-parallel: 1
      matrix:
        # arch: ['arm' ,'arm64' ,'x86' ,'x64']
        arch: ['arm']
    runs-on: ubuntu-latest
    name: ${{ matrix.arch }}
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: UTC
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      USE_CCACHE: 1
    container:
      image: kudo/ubuntu-nonroot:20.04
    steps:
      - name: Setup docker workspace
        run: |
            sudo sh -c "chown -R ubuntu $HOME"
            sudo sh -c "chmod 777 $GITHUB_WORKSPACE"
            sudo sh -c "chmod 777 /home"

      - uses: actions/checkout@v2

      - name: Setup Ubuntu environment
        run: |
          sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y sudo apt-utils sudo ccache lsb-core git python nodejs npm wget openjdk-8-jre openjdk-8-jdk
          git config --global user.email "git@job.com"; git config --global user.name "GitJob"

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - name: Setup Build  V8
        run: |
          ./scripts/setup-build.sh android
          sudo apt-get install -y libatomic1-i386-cross && sudo sh -c 'echo "/usr/i686-linux-gnu/lib" >> /etc/ld.so.conf.d/i386-linux-gnu.conf' && sudo ldconfig

      - name: Create libv8.json
        run: |
          source ./scripts/env.sh
          gitRevision=$(git -C v8 rev-parse HEAD)
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          MAJOR=$(grep "#define V8_MAJOR_VERSION" "v8/include/v8-version.h" | awk '{print $NF}' | tr -d '[[:space:]]')
          MINOR=$(grep "#define V8_MINOR_VERSION" "v8/include/v8-version.h" | awk '{print $NF}' | tr -d '[[:space:]]')
          BUILD=$(grep "#define V8_BUILD_NUMBER" "v8/include/v8-version.h" | awk '{print $NF}' | tr -d '[[:space:]]')
          PATCH=$(grep "#define V8_PATCH_LEVEL" "v8/include/v8-version.h" | awk '{print $NF}' | tr -d '[[:space:]]')
          echo "{
            \"version\": \"$MAJOR.$MINOR.$BUILD.$PATCH\",
            \"git_revision\": \"$gitRevision\",
            \"git_branch\": \"${{ env.BRANCH_NAME }}\",
            \"timestamp\": \"$timestamp\",
            \"ndkVersion\": \"$NDK_VERSION\",
            \"ndkApiLevel\": \"$NDK_API_LEVEL\"
          }" >> dist/${{ matrix.arch }}-release/libv8.json


      - name: Retrieve ccache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.arch }}-
            ${{ runner.os }}-ccache-

      - name: Build
        run: ./scripts/build.android.sh -l ${{ matrix.arch }}

      - name: Show summary of ccache configuration and statistics counters
        run: ccache --show-stats

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: libv8-release-${{ matrix.arch }}
          path: dist/${{ matrix.arch }}-release

  # Combine the various architecture builds with the headers and a custom libv8.json file
  package:
    runs-on: ubuntu-latest
    name: Package
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Download all workflow run artifsacts
        uses: actions/download-artifact@v2

      - name: Move built libraries to final folder
        run: |
          mv libv8-release-arm/generated build/release/generated
          mv libv8-release-arm/include build/release/include
          mv libv8-release-arm/v8_inspector build/release/v8_inspector
          mv libv8-release-arm/libv8.json build/release/libv8.json
          mkdir build/release/libs/arm && mv libv8-release-arm/*.a build/release/libs/arm
          # mkdir build/release/libs/arm64 && mv libv8-release-arm64/*.a build/release/libs/arm64
          # mkdir build/release/libs/x86 && mv libv8-release-x86/*.a build/release/libs/x86
          # mkdir build/release/libs/x64 && mv libv8-release-x64/*.a build/release/libs/x64

      - name: get v8 version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'build/release/libv8.json'
            prop_path: 'version'
          
      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: libv8-android-${{ steps.version.outputs.prop }}-release
          path: |
            build/release
          
      - name: Delete uneeded artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            libv8-release-arm
            # libv8-release-arm64
            # libv8-release-x86
            # libv8-release-x64
