name: Build for Android

on:
  push:
    branches:
      - master
  pull_request:

env:
  CACHE_KEY_SUFFIX: v2
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ubuntu environment
        run: |
          sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install curl build-essential g++-multilib
          git config --global user.email "git@job.com"; git config --global user.name "GitJob"

      - name: Setup Build  V8
        run: |
          sh ./scripts/setup-build 9.2.230.18

      - name: Build  V8
        run: |
          ./scripts/build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
